import BluetoothInspectorKit
import SwiftUI

struct OverviewTab: View {
    @Environment(AppModel.self) private var model
    let device: InspectedDevice

    var body: some View {
        let saved = model.workspace.history[device.id]
        Form {
            Section("Identity") {
                InfoRow("Name", device.name ?? "Unnamed")
                if let custom = saved?.customName { InfoRow("Local Name", custom, help: "Name you gave this device in Bluetooth Inspector") }
                if let systemName = device.systemName, systemName != device.name {
                    InfoRow("System Name", systemName, help: "GAP name cached by macOS")
                }
                InfoRow("Identifier", device.id.identifierString, monospaced: true,
                        help: device.transport == .lowEnergy
                            ? "CoreBluetooth peripheral UUID. It is generated by this Mac and is not the device's Bluetooth address."
                            : "Bluetooth device address (BD_ADDR)")
                InfoRow("Transport", device.transport.longTitle)
                if device.dualModeHint != .none {
                    InfoRow("Dual-mode", device.dualModeHint.explanation)
                }
                InfoRow("Manufacturer", device.manufacturer ?? "Unknown")
            }

            Section("Status") {
                InfoRow("Connection", connectionText)
                InfoRow("RSSI", device.rssi.map { "\($0) dBm" } ?? "—")
                InfoRow("First Seen", DisplayFormatting.dateTime(device.firstSeen))
                InfoRow("Last Seen", DisplayFormatting.dateTime(device.lastSeen))
                if let connectedAt = device.connectedAt {
                    InfoRow("Connected Since", DisplayFormatting.dateTime(connectedAt))
                }
                if device.transport == .lowEnergy {
                    InfoRow("Paired / Bonded", "Not exposed by CoreBluetooth",
                            help: "macOS does not tell apps whether a BLE peripheral is bonded. Pairing happens automatically when an encrypted attribute is accessed.")
                }
                if let error = device.lastError {
                    InfoRow("Last Error", error)
                }
            }

            if device.transport == .lowEnergy {
                Section("Advertising") {
                    InfoRow("Local Name", device.advertisement.localName ?? "—")
                    InfoRow("TX Power Level", device.advertisement.txPowerLevel.map { "\($0) dBm" } ?? "Not advertised")
                    InfoRow("Connectable", device.advertisement.isConnectable.map { $0 ? "Yes" : "No" } ?? "Unknown")
                    InfoRow("Advertised Services", device.advertisement.serviceUUIDs.map(\.displayName).joined(separator: ", "))
                    InfoRow("Packets Received", "\(device.advertisementPacketCount)")
                    InfoRow("Content Changes", "\(device.advertisementChangeCount)",
                            help: "How often the advertised fields changed (RSSI excluded)")
                }

                if device.connectionState == .connected || !device.gatt.isEmpty {
                    Section("GATT") {
                        InfoRow("Services", "\(device.gatt.primaryServices.count) primary, \(device.gatt.secondaryServices.count) secondary")
                        InfoRow("Characteristics", "\(device.gatt.characteristicCount)")
                        InfoRow("Notifying", "\(device.gatt.allCharacteristics.filter(\.isNotifying).count)")
                        if let maximum = device.maximumWriteLength {
                            InfoRow("Max Write (with response)", "\(maximum) bytes")
                        }
                        if let maximum = device.maximumWriteWithoutResponseLength {
                            InfoRow("Max Write (without response)", "\(maximum) bytes",
                                    help: "ATT MTU − 3, as negotiated for this connection")
                        }
                    }
                }
            }

            if let classic = device.classic {
                ClassicOverviewSection(classic: classic)
            }

            Section {
                LimitationsNote(transport: device.transport)
            } header: {
                Text("What macOS Does Not Expose")
            }
        }
        .formStyle(.grouped)
    }

    private var connectionText: String {
        if device.isSystemConnected && device.connectionState == .disconnected {
            return "Connected by the system (not by this app)"
        }
        if device.transport == .classic {
            return device.classic?.isConnected == true ? "Connected (baseband)" : "Not connected"
        }
        return device.connectionState.title
    }
}

struct ClassicOverviewSection: View {
    let classic: ClassicDeviceInfo

    var body: some View {
        Section("Bluetooth Classic") {
            InfoRow("Address", classic.address, monospaced: true)
            InfoRow("OUI", classic.oui, monospaced: true, help: "First three octets of a public address identify the manufacturer (IEEE OUI)")
            if let cod = classic.classOfDevice {
                InfoRow("Class of Device", "\(cod.hexString) · \(cod.majorName) – \(cod.minorName)")
                InfoRow("Service Classes", cod.serviceClasses.joined(separator: ", "))
            }
            InfoRow("Paired", classic.isPaired ? "Yes" : "No")
            InfoRow("Connected", classic.isConnected ? "Yes" : "No")
            InfoRow("Known From", classic.sources.map(\.rawValue).sorted().joined(separator: ", "))
            if let pnp = classic.pnpInformation {
                InfoRow("Vendor", pnp.vendorDescription)
                InfoRow("Product ID", String(format: "0x%04X", pnp.productID), monospaced: true)
                InfoRow("Version", pnp.versionString)
            }
            InfoRow("Profiles", classic.profileNames.joined(separator: ", "))
            InfoRow("Last Inquiry Update", DisplayFormatting.dateTime(classic.lastInquiryUpdate))
            InfoRow("Last Services Update", DisplayFormatting.dateTime(classic.lastServicesUpdate))
        }
    }
}

/// States platform limitations plainly instead of implying data exists.
struct LimitationsNote: View {
    let transport: BluetoothTransport

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            ForEach(items, id: \.self) { item in
                Label(item, systemImage: "info.circle")
                    .font(.callout)
                    .foregroundStyle(.secondary)
            }
        }
        .padding(.vertical, 2)
    }

    private var items: [String] {
        switch transport {
        case .lowEnergy:
            [
                "The device's Bluetooth address and address type (public/random) are hidden; the identifier is a per-Mac UUID.",
                "Raw advertising PDUs, AD flags, advertising interval, PHY and channel are not available; only CoreBluetooth's parsed fields.",
                "Bonding state is not reported, and pairing cannot be started directly.",
                "Some services are reserved by macOS (for example HID 0x1812) and never appear in service discovery.",
            ]
        case .classic:
            [
                "IOBluetooth exposes paired/recent devices, inquiry results, Class of Device and SDP records.",
                "RSSI is only available while a baseband connection exists.",
                "Pairing, link keys, and RFCOMM/L2CAP data channels are not used by this inspector.",
            ]
        }
    }
}
